services:
  wud:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Bangkok
      - WUD_LOG_LEVEL=info
      # เปิดใช้งาน Trigger ประเภท Docker ภายในโฮสต์
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      - WUD_TRIGGER_DOCKER_LOCAL_AUTO=true
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true
      - WUD_WATCHER_LOCAL_CRON=*/5 * * * *
    ports:
      - 3000:3000
    restart: unless-stopped

  portal-frontend:
    image: adashima/422-portal:latest
    container_name: 422_portal
    ports:
      - "422:422"
    labels:
      # บอก WUD ให้ watch Container นี้
      - "wud.watch=true"
    restart: always